import gymnasium as gym
from gymnasium import spaces
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional, Tuple, Dict, Sequence

class GoldenEyeEnv(gym.Env):
    """
    Custom Environment that follows gym interface.
    This environment consumes the cumulative moments generated by goldeneye_builder.py.
    """
    metadata = {'render_modes': ['human']}

    DEFAULT_TARGET_COLS = ("mean", "std", "skew", "kurtosis")
    DEFAULT_OBS_COLS = ("mean", "std", "skew", "kurtosis", "pct_change")

    def __init__(
        self,
        data_dir: str,
        symbol: str,
        bucket: str = "P3",
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        observation_cols: Optional[Sequence[str]] = None,
        target_cols: Optional[Sequence[str]] = None,
        reward_scale: float = 0.25,
        observation_bounds: Optional[Tuple[np.ndarray, np.ndarray]] = None,
    ):
        super().__init__()

        self.data_dir = Path(data_dir)
        self.symbol = symbol.upper()
        self.bucket = bucket.upper()
        self.start_date = start_date
        self.end_date = end_date
        self.observation_cols = tuple(observation_cols) if observation_cols else self.DEFAULT_OBS_COLS
        self.target_cols = tuple(target_cols) if target_cols else self.DEFAULT_TARGET_COLS
        self.reward_scale = reward_scale
        self._observation_bounds = None
        if observation_bounds is not None:
            low, high = observation_bounds
            self._observation_bounds = (
                np.asarray(low, dtype=np.float32),
                np.asarray(high, dtype=np.float32),
            )

        # Load and optionally filter data
        self.df = self._load_data()
        if self.start_date or self.end_date:
            self.df = self._apply_date_filters(self.df, self.start_date, self.end_date)
        if len(self.df) < 2:
            raise ValueError(f"Not enough rows to run environment for {self.symbol} after filtering")

        self.observation_space = self._make_observation_space()
        self.action_space = self._make_action_space()

        self.current_step = 0
        self.terminated = False
        
    def _load_data(self) -> pd.DataFrame:
        # Try daily first
        file_path = self.data_dir / "daily" / self.bucket / self.symbol / "cumulative_moments.csv"
        if not file_path.exists():
            # Try hourly
            file_path = self.data_dir / "hourly" / self.bucket / self.symbol / "cumulative_moments.csv"
            
        if not file_path.exists():
            raise FileNotFoundError(f"Data file not found for {self.symbol} in {self.bucket} at {self.data_dir}")
            
        df = pd.read_csv(file_path)
        # Ensure required columns exist
        required = ['mean', 'std', 'skew', 'kurtosis', 'pct_change']
        if not all(col in df.columns for col in required):
            raise ValueError(f"Data file missing columns. Found: {df.columns}")
            
        # Ensure datetime dtype for filtering/infos
        if 'date' in df.columns:
            df['date'] = pd.to_datetime(df['date'], utc=True, errors='coerce')

        # Fill NaNs if any (first few rows might have NaNs for moments)
        df = df.fillna(0)
        return df

    @staticmethod
    def _apply_date_filters(df: pd.DataFrame, start: Optional[str], end: Optional[str]) -> pd.DataFrame:
        if 'date' not in df.columns:
            return df
        filtered = df
        if start:
            start_ts = pd.Timestamp(start, tz='UTC')
            filtered = filtered[filtered['date'] >= start_ts]
        if end:
            end_ts = pd.Timestamp(end, tz='UTC')
            filtered = filtered[filtered['date'] < end_ts]
        return filtered.reset_index(drop=True)

    def reset(self, seed: Optional[int] = None, options: Optional[dict] = None) -> Tuple[np.ndarray, dict]:
        super().reset(seed=seed)
        self.current_step = 0
        self.terminated = False
        observation = self._get_observation()
        info = self._get_info()
        return observation, info

    def step(self, action: np.ndarray) -> Tuple[np.ndarray, float, bool, bool, dict]:
        if self.terminated:
            raise RuntimeError("Episode already terminated. Call reset() before calling step().")

        if self.current_step >= len(self.df) - 1:
            # No future row to compare against; terminate with zero reward
            self.terminated = True
            return self._get_observation(), 0.0, True, False, self._get_info()

        prediction = np.asarray(action, dtype=np.float32).reshape(-1)
        if prediction.shape[0] != len(self.target_cols):
            raise ValueError(
                f"Expected action with {len(self.target_cols)} values (for {self.target_cols}), got {prediction.shape}"
            )

        next_row = self.df.iloc[self.current_step + 1]
        actual = next_row[list(self.target_cols)].to_numpy(dtype=np.float32)
        squared_errors = (prediction - actual) ** 2
        reward = -self.reward_scale * float(np.sum(squared_errors))

        self.current_step += 1
        if self.current_step >= len(self.df) - 1:
            self.terminated = True

        observation = self._get_observation()
        info = self._get_info(additional={
            "prediction": prediction,
            "actual": actual,
            "squared_error": squared_errors,
        })

        return observation, reward, self.terminated, False, info

    def _get_observation(self) -> np.ndarray:
        row = self.df.iloc[self.current_step]
        obs = row[list(self.observation_cols)].to_numpy(dtype=np.float32)
        return obs

    def _get_info(self, additional: Optional[Dict[str, np.ndarray]] = None) -> dict:
        info = {
            "step": int(self.current_step),
            "date": self.df.iloc[self.current_step]['date'] if 'date' in self.df.columns else "",
        }
        if additional:
            info.update(additional)
        return info

    def _make_observation_space(self) -> spaces.Box:
        if self._observation_bounds is not None:
            low, high = self._observation_bounds
            return spaces.Box(low=low, high=high, dtype=np.float32)
        values = self.df[list(self.observation_cols)].to_numpy(dtype=np.float32)
        obs_min = np.min(values, axis=0)
        obs_max = np.max(values, axis=0)
        # Ensure a little breathing room even if a column is constant
        epsilon = 1e-3
        tight = (obs_max - obs_min) < epsilon
        obs_min[tight] -= epsilon
        obs_max[tight] += epsilon
        return spaces.Box(low=obs_min, high=obs_max, dtype=np.float32)

    def _make_action_space(self) -> spaces.Box:
        targets = self.df[list(self.target_cols)].to_numpy(dtype=np.float32)
        max_abs = np.max(np.abs(targets), axis=0)
        # In case a column is zero everywhere, fall back to +/-1 range
        max_abs = np.where(max_abs == 0, 1.0, max_abs)
        bounds = max_abs * 2.0  # allow some headroom beyond observed range
        return spaces.Box(low=-bounds, high=bounds, dtype=np.float32)

    def render(self):
        info = self._get_info()
        date = info.get("date", "")
        print(f"Step: {self.current_step}, Date: {date}")

if __name__ == "__main__":
    # Simple test
    import sys
    
    # Default paths
    data_root = "D:/Trading Strategies/GoldenEye"
    symbol = "TIMETECHNO" # We know this exists from previous step
    bucket = "P3"
    
    try:
        env = GoldenEyeEnv(data_root, symbol, bucket)
        obs, info = env.reset()
        print(f"Reset Observation: {obs}")
        
        for _ in range(5):
            action = env.action_space.sample()
            obs, reward, term, trunc, info = env.step(action)
            print(f"Step: {info['step']}, Action: {action}, Reward: {reward:.4f}, Value: {info['portfolio_value']:.2f}")
            if term or trunc:
                break
                
        print("Environment test passed.")
    except Exception as e:
        print(f"Environment test failed: {e}")
